baseurl             = "https://numbat.netlify.com/" # Must end with /
languageCode        = "en-us"
title               = "NUMBAT"
theme               = "hugo-theme-introduction"
enforce_ssl         = "numbat.space"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# disqusshortname   = "" # Enable Disqus for comments
# googleAnalytics   = ""

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "numbats" # Full name shows on blog post pages
firstname     = "NUMBAT" # First name shows in introduction on main page
tagline       = "News and Updates of the Monash Business Analytics Team" # Appears after the introduction
introheight   = "medium" # Input either 'medium' or 'large' or 'fullheight'
theme         = "dark" # Choose 'light' or 'dark'
avatar        = "img/numbat.png" # Path to image in static folder eg. img/avatar.png 
email         = "" # Shows in contact section, or leave blank to omit
localtime     = true # Show your current local time in contact section
timezone      = "Australia/Melbourne" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "News and Updates of the Monash Business Analytics Team"
faviconfile   = "img/fav.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "Copyright ©2016-7 Monash University Business Analytics Team, Econometrics and Business Statistics, Monash University, Australia" # Text to show in footer (overrides default text)
fadein        = true # Turn on/off the fade-in effect
extracssfiles = ["css/custom.css"]

showblog        = false # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = false # Show latest blog post summary
sharebuttons    = false # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "http://www.datasciencemelbourne.com/medascin2017/"
project1img     = "img/project1.jpg"
project1title   = "WOMBAT MeDaScin 2017"

project2link    = "http://www.monash.edu/news/articles/team-profile-monash-business-analytics-team"
project2img     = "img/numbat.png"
project2title   = "Feature in Monash newsletter The Insider"

project3link    = "http://dicook.org/WOMBAT/"
project3img     = "img/wombat-icon-web.png"
project3title   = "WOMBAT 2016"


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
url = ""
icon = ""

[[params.social]]
url = ""
icon = ""
